name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pytmx pyinstaller
    
    - name: Copy files to build directory
      run: |
        xcopy code\*.py . /Y
        dir
    
    - name: Build executable with all modules
      run: |
        pyinstaller --name="AIF_Project" --onefile --windowed --add-data="data;data" --add-data="graphics;graphics" --hidden-import=pytmx.util_pygame --hidden-import=pygame --hidden-import=random --hidden-import=math main.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: AIF_Project-Windows
        path: dist/AIF_Project.exe
